### ISSUE TITLE
An error has been occurred. Retrying...

### ISSUE THREAD

**Issue by Mafiosoweb1** [asimptot/FollowerBot#63]
Hi, Im pretty new to coding. Everything was working few days ago and recently this started to happen. Im on Mint and I have everything downloaded.
![image](https://user-images.githubusercontent.com/69605438/220977756-a30a3147-8108-4e7c-ab17-0a3dd36e9126.png)

I wasnt doing anything to the code, also tried to reinstall it. nothing worked.

**Comment by asimptot** [comment]
@Mafiosoweb1 hi,

Please use the latest code. I've updated it.

https://github.com/asimptot/FollowerBot/commit/5127ba1c5fa17173a54d961737cb13bdfb221f6f

**Comment by Mafiosoweb1** [comment]
Awesome, followers really do work now, thanks for that, but now it appears the likes have stopped working

![image](https://user-images.githubusercontent.com/69605438/220998466-c8a7ce76-7704-47c9-8c65-c42f7654df08.png)
Thanks for the followers fix. <3

**Comment by Mafiosoweb1** [comment]
I have downloaded the newest version it still doesnt work.
![image](https://user-images.githubusercontent.com/69605438/221006595-dd8579f5-3d9c-4a92-8586-e946b9295d3f.png)

**Comment by asimptot** [comment]
Please use the latest code for likes. I've just committed.

https://github.com/asimptot/FollowerBot/commit/aa5b2bdfe152817e17aed50a30e9d6afc4f3cb55

You should wait 1000 seconds after you entered username or post link.

**Comment by Mafiosoweb1** [comment]
Again downloaded newest version and its still not working, im i doing something wrong?
![Snímek obrazovky 2023-02-23 203636](https://user-images.githubusercontent.com/69605438/221012137-da929a38-56c0-472a-95d1-28bca312036f.png)

**Comment by asimptot** [comment]
As I told you in the above, you should wait 1000 seconds for it.

**Comment by Mafiosoweb1** [comment]
I've waited this is result after 1000 seconds

**Comment by asimptot** [comment]
Can you run it in non headless mode, please?

**Comment by Mafiosoweb1** [comment]
How can i do that?

**Comment by Mafiosoweb1** [comment]
Ok did that its runnin.
![image](https://user-images.githubusercontent.com/69605438/221014294-661f7419-9ec4-4a36-b52c-352220eecb48.png)

**Comment by Mafiosoweb1** [comment]
![image](https://user-images.githubusercontent.com/69605438/221019528-d14e2005-488b-4c1a-9db4-40959b765bd9.png)
So the test completed but program didnt register it.

**Comment by asimptot** [comment]
The failure has been reproduced and fixed on my side. Please use the latest code.

https://github.com/asimptot/FollowerBot/commit/6ce65a1f1ba6c0fa12e8b7e20802242fe75d373c

**Comment by adas71** [comment]
And what about likes ?

**Comment by asimptot** [comment]
You can use the latest code. It's already fixed!
